Update installwhatsapp

diff --git a/installwhatsapp b/installwhatsapp
--- a/installwhatsapp
+++ b/installwhatsapp
@@ -1,5 +1,28 @@
 #!/bin/bash
 
+#Identifying the system package manager
+declare -A osInfo;
+osInfo[/etc/redhat-release]=yum
+osInfo[/etc/arch-release]=pacman
+osInfo[/etc/gentoo-release]=emerge
+osInfo[/etc/SuSE-release]=zypp
+osInfo[/etc/debian_version]=apt
+
+for f in ${!osInfo[@]}
+do
+    if [[ -f $f ]]; then
+        echo Package manager: ${osInfo[$f]} 
+        packagemanager=${osInfo[$f]}
+    fi
+done
+
+if packagemanager=zypp; then sudo apt update
+elif packagemanager=dnf; then sudo dnf 
+elif packagemanager=apt; then sudo yum update
+elif packagemanager=zypp; then sudo 
+else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2; fi
+
+
 #Download prerequisites to nativefy WhatsApp
 echo -e '\e[32mPreparing...\e[39m'
 wget -qO- https://deb.nodesource.com/setup_16.x | sudo bash -
