Update install-whatsapp

diff --git a/install-whatsapp b/install-whatsapp
--- a/install-whatsapp
+++ b/install-whatsapp
@@ -15,13 +15,19 @@ echo -e "\\n\\n"
 
 sleep 5s
  
-# A simple error function
+# A simple function to display error messages
 function error {
   echo -e "\\e[41;30m$1\\e[0m"
   exit 1 
 }
 
-# A simple success function
+# A simple 
+function progress {
+  echo -e "\\e[34m#####################################################\\e[0m\\n\\e[96m$1\\e[0m\\n\\e[34m#####################################################\\e[0m"
+}
+
+
+# A simple function to display success messages
 function success {
   echo -e "\\e[102;30m$1\\e[0m"
 }
@@ -42,68 +48,71 @@ function log {
 }
 
 # Create new WhatsApp directory and a blank file to store logs 
+progress "Creating new folder in '$HOME' folder..."
+echo ""
+echo "Removing 'WhatsApp' folder from $HOME if exists."
 sudo rm -rf "${HOME}/WhatsApp" 2> /dev/null
+sleep 1s
+echo "Creating folder..."
 mkdir "${HOME}/WhatsApp" || error  "Failed creating folder in your home folder."
 directory="${HOME}/WhatsApp"
+echo "cd to $directory"
 cd "$directory" | log || error  "Failed to cd to $directory"
+echo "Creating log file..."
 touch log.txt
+sleep 1
+echo -e "\n"
+
+
+# Identify the system package manager and update package list
+progress "Identifying your system package manager..."
 echo ""
-
-
-# Identifying the system package manager
 if command -v apt > /dev/null; then
     packagemanager=apt
     success "Your package manager is $packagemanager"
-    echo -e "\\n\\n"    
-    success "Updating package list..."
+    echo -e "\\n"    
+    progress "Updating package list..."
     ( sudo $packagemanager update 2>&1 | log || error "Failed updating package list." ) | reduceoutput
-    echo -e "\n"
-    success "Installing wget and curl..."
-    echo ""
-    ( sudo $packagemanager install wget curl git -y 2>&1 || error "Failed installing wget and curl." ) 
     echo -e "\n"
 elif command -v dnf > /dev/null; then
     packagemanager=dnf
     success "Your package manager is $packagemanager"
-    sudo $packagemanager check-update | log
-    sudo $packagemanager install curl -y | log || error  "Failed installing curl."
-    sudo $packagemanager install wget -y | log || error  "Failed installing wget."
-    sudo $packagemanager install git -y | log || error  "Failed installing git."
+    sudo $packagemanager check-update 2>&1 > /dev/null | log
 elif command -v yum > /dev/null; then
     packagemanager=yum
     success "Your package manager is $packagemanager"
-    sudo $packagemanager check-update  | log
-    sudo $packagemanager install curl -y | log || error  "Failed installing curl."
-    sudo $packagemanager install wget -y | log || error  "Failed installing wget."
-    sudo $packagemanager install git -y | log || error  "Failed installing git."
+    sudo $packagemanager check-update 2>&1 > /dev/null | log
 else
     error "Package manager not found. This script only support apt, yum and dnf."
 fi
 
 
-# Installing Nodejs using snapd
+# Install snapd if not installed
 if ! command -v snap > /dev/null; then
+    progress "Installing snap..."
     sudo $packagemanager install snapd -y | reduceoutput
-    sudo snap install node --classic
-    if command -v node > /dev/null &&  command -v npm > /dev/null ; then 
-        success "Nodejs installed sucessfully."
-    fi
+else 
+    success "Snap is already installed."
+fi
+
+# Installing node using snap
+sudo snap install node --classic
+if command -v node > /dev/null && command -v npm > /dev/null ; then 
+    success "Nodejs installed sucessfully."
+else 
+    error "Failed installing NodeJS. Try Try running 'sudo snap install node --classic' and run this script again."
 fi
 
 # Installing Nativefier
-if command -v npm > /dev/null; then
-    if ! command -v nativefier > /dev/null; then
-        success "Installing Nativefier..."
-        npm install -g nativefier | log || error  "Failed installing Nativefier. Try running 'npm install -g nativefier' and run this script again."
-        cd "${HOME}/WhatsApp" | log || error  "Failed cd to WhatsApp folder."
-        if command -v nativefier > /dev/null; then
-            success "Nativefier installed successfully."
-        fi
-    else 
-        success "Nativefier is already installed."
-    fi
-else
-    error "Failed. NPM not found. Try running 'sudo snap install node --classic' and run this script again."
+if ! command -v nativefier > /dev/null; then
+    success "Installing Nativefier..."
+    npm install -g nativefier | log || error  "Failed installing Nativefier. Try running 'npm install -g nativefier' and run this script again."
+cd "${HOME}/WhatsApp" | log || error  "Failed cd to WhatsApp folder."
+if command -v nativefier > /dev/null; then
+success "Nativefier installed successfully."
+fi
+else 
+success "Nativefier is already installed."
 fi
 
 # Identifying architecture
@@ -133,7 +142,7 @@ echo -e "\n\n"
 
 # Nativefying WhatsApp
 if command -v nativefier > /dev/null; then
-    success "Nativefying WhatsApp from http://web.whatsapp.com ..."
+    progress "Nativefying WhatsApp from http://web.whatsapp.com ..."
     cd "$directory" || error "Failed to cd to $directory"
     (nativefier https://web.whatsapp.com --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" -a "$arch" --maximize -n WhatsApp ) 
     echo -e "\n"
@@ -145,7 +154,7 @@ fi
 echo -e "\n"
 
 # Create desktop & menu shortcut
-success "Creating desktop shortcut and menu shortcut..."
+progress "Creating desktop shortcut and menu shortcut..."
 echo ""
 cd "$directory" || error "Failed to cd to $directory."
 git clone https://github.com/ITdairy/whatsapp-for-linux -v
