Update installwhatsapp

diff --git a/installwhatsapp b/installwhatsapp
--- a/installwhatsapp
+++ b/installwhatsapp
@@ -1,7 +1,6 @@
 #!/bin/bash
 
 # Identifying the system package manager
-
 if [ -e /usr/bin/apt ]; then
 	packagemanager=apt
 	echo -e "\e[32mPackage manager: $packagemanager\e[0m" 
@@ -18,21 +17,20 @@ fi
 
 # Updating package list
 if $packagemanager=apt; then
-    sudo apt update 
+	sudo apt update 
 elif $packagemanager=yum; then
-    sudo yum check-update
+	sudo yum check-update
 elif $packagemanager=dnf; then
-    sudo dnf check-update
+	sudo dnf check-update
 fi
-
 
 
 # Checking prerequisites to nativefy WhatsApp
 echo -e "\e[30;42mChecking prerequisites to nativefy WhatsApp\e[0m"
 
-# Installing Nodejs and NPM
 
-if [ -e /usr/bin/nodejs ] ; [ -e /usr/bin/npm ]; then
+# Installing Nodejs and NPM
+if ! command -v nodejs npm ; then
 	nodejsversion=$(nodejs -v | tr -dc '0-9, .'| head -c 2)
 	npmversion=$(npm -v | head -c 1)
 		if (($nodejsversion>=13)) && (($npmversion>=7)); then
@@ -68,22 +66,31 @@ else
             fi
 fi
 
+
 # Installing Nativefier
-if [ -e 
-npm install -g nativefier
-sudo mkdir WhatsApp
-cd Whatsapp
-wget https://raw.githubusercontent.com/ITdairy/whatsapp-nativefier-script/main/run-whatsapp.sh
-wget https://raw.githubusercontent.com/ITdairy/whatsapp-nativefier-script/main/whatsapp.desktop
- 
+if command -v npm > /dev/null; then
+	npm install -g nativefier
+	sudo mkdir ~/WhatsApp
+	cd ~/WhatsApp
+	wget https://raw.githubusercontent.com/ITdairy/whatsapp-for-linux/main/run-whatsapp.sh
+	wget https://raw.githubusercontent.com/ITdairy/whatsapp-for-linux/main/whatsapp.desktop
+else
+	echo "Failed"
+fi
+
+
 #Nativefier WhatsApp with user agent
-echo -e '\e[32mNativefying WhatsApp from http://web.whatsapp.com ...\e[39m'
-nativefier https://web.whatsapp.com --user-agent "Mozilla/5.0 (X11; CrOS armv7l 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.187 Safari/537.36" -a `uname -m` --maximize -n WhatsApp
-cd ./WhatsApp-linux-`uname -m`
-sudo cp ../run-whatsapp.sh ./
-sudo chmod +x ./run-whatsapp.sh
-cd ..
-echo -e '\e[32mDone installing WhatsApp, Creating desktop shortcut and menu shortcut...'
+if command -v nativefier > /dev/null; then
+	echo -e '\e[32mNativefying WhatsApp from http://web.whatsapp.com ...\e[39m'
+	nativefier https://web.whatsapp.com --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" -a `uname -m` --maximize -n WhatsApp
+	cd ./WhatsApp-linux-`uname -m`
+	sudo cp ../run-whatsapp.sh ./
+	sudo chmod +x ./run-whatsapp.sh
+	cd ..
+	echo -e '\e[32mDone installing WhatsApp, Creating desktop shortcut and menu shortcut...'
+else 
+	echo "Failed"
+
 
 #Create desktop & menu shortcut
 sudo cp ./whatsapp.desktop /usr/share/applications
