Update install-whatsapp

diff --git a/install-whatsapp b/install-whatsapp
--- a/install-whatsapp
+++ b/install-whatsapp
@@ -18,7 +18,7 @@ function reduceoutput {
 
 # Log errors
 function log {
-  tee $directory/log.txt
+  tee "$directory/log.txt"
 }
 
 # Check if user using root privilege to run this script
@@ -26,19 +26,20 @@ if [[ "$(id -u)" == 0 ]]; then
 	error "This script is not designed to be runned as root! Please try again as a regular user." 
 fi
 
-sudo rm -rf "${HOME}/WhatsApp" 2>&1 > /dev/null
+# Create new WhatsApp directory and a blank file to store logs 
+sudo rm -rf "${HOME}/WhatsApp" 2> /dev/null
 sudo mkdir "${HOME}/WhatsApp" | log || error  "Failed creating folder in your home folder."
 directory="${HOME}/WhatsApp"
-cd $directory | log || error  "Failed to cd to $directory"
+cd "$directory" | log || error  "Failed to cd to $directory"
 touch log.txt
 echo ""
 
 # Identifying the system package manager
 if command -v apt > /dev/null; then
     packagemanager=apt
-    echo -e "\\e[32mPackage manager is $packagemanager\n\n\nUpdating package list...\\e[0m"
+    echo -e "\\e[32mPackage manager is $packagemanager\\n\\n\\nUpdating package list...\\e[0m"
     ( sudo $packagemanager update 2>&1 | log || error "Failed updating package list." ) | reduceoutput 
-    echo -e  "\n\n\\e[32mInstalling wget and curl...\\e[0m"
+    echo -e  "\\n\\n\\e[32mInstalling wget and curl...\\e[0m"
     ( sudo $packagemanager install wget curl -y 2>&1 || error "Failed installing wget and curl" ) | reduceoutput
 elif command -v dnf > /dev/null; then
     packagemanager=dnf
@@ -60,9 +61,10 @@ fi
 if ! command -v snap > /dev/null; then
     sudo $packagemanager install snapd -y
     sudo snap install node --classic
-    if $(command -v node > /dev/null) &&  $(command -v npm > /dev/null) ; then 
+    if command -v node > /dev/null &&  command -v npm > /dev/null ; then 
         success "Nodejs installed sucessfully."
     fi
+fi
 
 # Installing Nativefier
 if command -v npm > /dev/null; then
@@ -92,7 +94,7 @@ fi
 #Nativefying WhatsApp
 if command -v nativefier > /dev/null; then
     success "Nativefier installed successfully."
-    echo -e "\\e[32m\n\nNativefying WhatsApp from http://web.whatsapp.com ...\\e[39m"
+    echo -e "\\e[32m\\n\\nNativefying WhatsApp from http://web.whatsapp.com ...\\e[39m"
     (nativefier https://web.whatsapp.com --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" -a "$arch" --maximize -n WhatsApp ) 2>&1 | reduceoutput
     sudo touch run-whatsapp
     echo "sudo rm -rf ${HOME}/.config/whatsapp-nativefier-*/Service Worker && $HOME/WhatsApp/WhatsApp-linux-$(uname -m)/WhatsApp" > ./run-whatsapp
