Update and rename installwhatsapp to install-whatsapp

diff --git a/install-whatsapp b/install-whatsapp
--- a/install-whatsapp
+++ b/install-whatsapp
@@ -1,24 +1,42 @@
 #!/usr/bin/env bash
 
+# A simple error function
 function error {
-  echo -e "\\e[41;5m$1\\e[0m"
+  echo -e "\\e[41;30m$1\\e[0m"
   exit 1 
 }
 
+# A simple success function
+function success {
+  echo -e "\\e[102;30m$1\\e[0m"
+}
+
+# To reduce annoying stderr output by apt & nativefier
 function reduceoutput { 
   grep -v "apt does not have a stable CLI interface.\\|Hit\\|Packaging\\|Preparing\\|Converting\\|Finalizing\\|App built to\\|shortcuts are up to you\\|to remove\\|Reading package lists...\\|newest version\\|Building dependency tree\\|Reading state information...\\|Need to get\\|After this operation,\\|Get:\\|Fetched\\|Selecting previously unselected package\\|Preparing to unpack\\|Unpacking \\|Setting up \\|Processing triggers for "
 }
 
-cd "${HOME}" || exit 1 
+# Log errors
+function log
+  tee 
 
+# Check if user using root privilege to run this script
+if [[ "$(id -u)" == 0 ]]; then
+	error "This script is not designed to be runned as root! Please try again as a regular user." 
+fi
+
+sudo rm -rf "${HOME}/WhatsApp" 2>&1 > /dev/null
+sudo mkdir "${HOME}/WhatsApp" || error "Failed creating folder in your home folder."
+directory="${HOME}/WhatsApp"
+cd $directory || error "Failed to cd to $directory"
 echo ""
-
 
 # Identifying the system package manager
 if command -v apt > /dev/null; then
     packagemanager=apt
     echo -e "\\e[32mPackage manager is $packagemanager\n\n\nUpdating package list...\\e[0m"
-    ( sudo $packagemanager update 2>&1 || error "Failed updating package list." ) | reduceoutput && echo -e  "\n\n\\e[32mInstalling wget and curl...\\e[0m"
+    ( sudo $packagemanager update 2>&1 || error "Failed updating package list." ) | reduceoutput 
+    echo -e  "\n\n\\e[32mInstalling wget and curl...\\e[0m"
     ( sudo $packagemanager install wget curl -y 2>&1 || error "Failed installing wget and curl" ) | reduceoutput
 elif command -v dnf > /dev/null; then
     packagemanager=dnf
@@ -36,37 +54,29 @@ else
 fi
 
 
-# Installing Nodejs and NPM
-if [ $packagemanager == 'apt' ]; then
-        echo -e "\\e[32mAdding NodeSource...\\e[0m"
-        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - > /dev/null || error "Failed adding NodeSource. Try running 'curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - ' and run this script again. "
-        echo -e "\\e[32m\\n\\nRunning sudo apt update and sudo apt install nodejs -y...\\e[0m"
-        ( sudo $packagemanager update || error "Failed updating package list." ) 2>&1 | reduceoutput
-        ( sudo $packagemanager install nodejs -y || error "Failed updating package list." ) 2>&1 | reduceoutput
-    else
-        echo -e "\\e[32mAdding NodeSource...\\e[0m"
-        curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash - > /dev/null || error "Failed adding NodeSource. Try running 'curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash - ' and run this script again."
-        echo -e "\\e[32mRunning sudo $packagemanager check-update and sudo $packagemanager install nodejs -y...\\e[0m"
-        ( (sudo $packagemanager check-update && sudo $packagemanager install nodejs -y ) > /dev/null )  || error "Failed installing Nodejs. Try running 'sudo $packagemanager install nodejs' and run this script again."
-fi
-
-
+# Installing Nodejs using snapd
+if ! command -v snap > /dev/null; then
+    sudo $packagemanager install snapd -y
+    sudo snap install node --classic
+    if $(command -v node > /dev/null) &&  $(command -v npm > /dev/null) ; then 
+        success "Nodejs installed sucessfully."
+    fi
 
 # Installing Nativefier
 if command -v npm > /dev/null; then
     if ! command -v nativefier > /dev/null; then
         echo -e "\\e[32mInstalling Nativefier...\\e[0m"
         npm install -g nativefier || error "Failed installing Nativefier. Try running 'npm install -g nativefier' and run this script again."
-        sudo mkdir "${HOME}/WhatsApp" || error "Failed creating folder in your home folder."
         cd "${HOME}/WhatsApp" || error "Failed cd to WhatsApp folder."
-        wget -qo- https://raw.githubusercontent.com/ITdairy/whatsapp-for-linux/main/run-whatsapp.sh 
-        wget -qo- https://raw.githubusercontent.com/ITdairy/whatsapp-for-linux/main/whatsapp.desktop 
-        wget -qo- https://github.com/ITdairy/whatsapp-for-linux/raw/main/whatsapp.png 
+        wget -qo-  https://raw.githubusercontent.com/ITdairy/whatsapp-for-linux/main/run-whatsapp.sh  https://raw.githubusercontent.com/ITdairy/whatsapp-for-linux/main/whatsapp.desktop https://raw.githubusercontent.com/ITdairy/whatsapp-for-linux/main/whatsapp.png | error "Failed to download files."
+        if command -v nativefier > /dev/null; then
+            success "Nativefier installed successfully."
+        fi
     else 
-        echo -e "\\e[32mNativefier is already installed.\\e[0m"
+        success "\\e[32mNativefier is already installed.\\e[0m"
     fi
 else
-    error "Failed. NPM not found. Try running 'sudo $packagemanager install nodejs' and run this script again."
+    error "Failed. NPM not found. Try running 'sudo snap install node --classic' and run this script again."
 fi
 
 # Identifying architecture
@@ -79,6 +89,7 @@ fi
 
 #Nativefying WhatsApp
 if command -v nativefier > /dev/null; then
+    success "Nativefier installed successfully."
     echo -e "\\e[32m\n\nNativefying WhatsApp from http://web.whatsapp.com ...\\e[39m"
     (nativefier https://web.whatsapp.com --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" -a "$arch" --maximize -n WhatsApp ) 2>&1 | reduceoutput
     sudo touch run-whatsapp
