Update install-whatsapp

diff --git a/install-whatsapp b/install-whatsapp
--- a/install-whatsapp
+++ b/install-whatsapp
@@ -37,15 +37,15 @@ function reduceoutput {
   grep -v "apt does not have a stable CLI interface."
 }
 
-# Log errors
-function log {
-  tee "$directory/log.txt"
-}
-
 # Check if user using root privilege to run this script
 if [[ "$(id -u)" == 0 ]]; then
 	error "This script is not designed to be runned as root! Please try again as a regular user." 
 fi
+
+# Log errors
+function log {
+  tee "$directory/log.txt"
+}
 
 # Create new WhatsApp directory and a blank file to store logs 
 progress "Creating new folder in '$HOME' folder..."
@@ -63,7 +63,7 @@ touch log.txt
 sleep 1
 echo ""
 success "Successfully created folder and log file."
-echo -e "\n"
+echo -e "\\n"
 
 
 # Identify the system package manager and update package list
@@ -71,7 +71,7 @@ progress "Identifying your system package manager..."
 echo ""
 if command -v apt > /dev/null; then
     packagemanager=apt
-    echo -e "Your package manager is \e[4m$packagemanager\e[0m"
+    echo -e "Your package manager is \\e[4m$packagemanager\\e[0m"
     echo ""
     success "Successfully identified system package manager."
     echo -e "\\n"    
@@ -79,7 +79,7 @@ if command -v apt > /dev/null; then
     ( sudo $packagemanager update 2>&1 | log || error "Failed updating package list." ) | tail -n +3
     echo ""
     success "Successfully updated package list."
-    echo -e "\n"
+    echo -e "\\n"
 elif command -v dnf > /dev/null; then
     packagemanager=dnf
     success "Your package manager is $packagemanager"
@@ -96,18 +96,18 @@ sleep 1
 
 # Install snapd if not installed
 progress "Installing snap..."
-echo -e "\n"
+echo -e "\\n"
 if ! command -v snap > /dev/null; then
     sudo $packagemanager install snapd -y | tail -n +3
 else 
     success "Snap is already installed."
 fi
 
-echo -e "\n"
+echo -e "\\n"
 
 # Installing node using snap
 progress "Installing node..."
-echo -e "\n"
+echo -e "\\n"
 # Uninstall nodejs node and npm first if exists
 sudo $packagemanager remove nodejs npm -y > /dev/null 2> /dev/null 
 nodeinstalled=$(snap info node | grep -o 'installed')
@@ -122,11 +122,11 @@ else
     fi
 fi 
 
-echo -e "\n"
+echo -e "\\n"
 
 # Installing Nativefier
 progress "Installing Nativefier..."
-echo -e "\n"
+echo -e "\\n"
 sudo ln -sfn /snap/node/current/bin/node /usr/bin/node || error "Failed make soft link to /usr/bin."
 if ! command -v nativefier > /dev/null; then
     sudo /snap/bin/npm install -g nativefier | log || error  "Failed installing Nativefier. Try running 'npm install -g nativefier' or 'sudo /snap/bin/npm install -g nativefier' and run this script again."
@@ -166,7 +166,7 @@ if [ "$arch" = "arm" ]; then
 fi 
 
 
-echo -e "\n"
+echo -e "\\n"
 
 # Nativefying WhatsApp
 if command -v nativefier > /dev/null; then
@@ -176,30 +176,29 @@ if command -v nativefier > /dev/null; then
     echo -e ""
     success "Successfully nativefied WhatsApp."
 else
-    error "Failed. Nativefier not found. Try running 'npm install -g nativefier' or with root 'sudo npm install -g nativefier' and run this script again. "
+    error "Failed. Nativefier not found. Try running 'npm install -g nativefier' or with root ' npm install -g nativefier' and run this script again. "
 fi
 
-echo -e "\n"
+echo -e "\\n"
 
 # Create desktop & menu shortcut
 progress "Creating desktop shortcut and menu shortcut..."
 echo ""
-if  ! [ "$(pwd)" == $directory ]; then 
+if  ! [ "$(pwd)" == "$directory" ]; then 
     cd "$directory" || error "Failed to cd to $directory."
 fi
 git clone https://github.com/ITdairy/whatsapp-for-linux -v
-echo -e "\n"
-sudo cp $directory/whatsapp-for-linux/* ./ && sudo rm -rf $directory/whatsapp-for-linux
-sed -i "s@HOME@$HOME@g" $directory/whatsapp.desktop
-sed -i "s@HOME@$HOME@g" $directory/run-whatsapp
-sed -i "s@arch@$arch@g" $directory/whatsapp.desktop 
-sed -i "s@arch@$arch@g" $directory/run-whatsapp
-sudo cp $directory/whatsapp.desktop "$HOME/.local/share/applications" | log
-sudo cp $directory/whatsapp.desktop "$HOME/Desktop" | log
-sudo cp $directory/run-whatsapp $directory/WhatsApp-linux-$arch
-sudo chmod +x $directory/WhatsApp-linux-$arch/run-whatsapp
+echo -e "\\n"
+sudo cp "$directory"/whatsapp-for-linux/* ./ && sudo rm -rf "$directory"/whatsapp-for-linux
+sed -i "s@HOME@$HOME@g" "$directory"/whatsapp.desktop 
+sed -i "s@arch@$arch@g" "$directory"/whatsapp.desktop 
+sed -i "s@arch@$arch@g" "$directory"/run-whatsapp
+sudo cp "$directory"/whatsapp.desktop "$HOME/.local/share/applications" | log
+sudo cp "$directory"/whatsapp.desktop "$HOME/Desktop" | log
+sudo cp "$directory"/run-whatsapp "$directory"/WhatsApp-linux-$arch
+sudo chmod +x "$directory"/WhatsApp-linux-$arch/run-whatsapp
 success "Successfully created desktop and menu shortcut."
-echo -e "\n\n"
+echo -e "\\n\\n"
 success "Done! You should be able to run WhatsApp from desktop and menu bar."
-echo -e "\n\n"
+echo -e "\\n\\n"
 cd "$HOME"  || exit 
