Update install-whatsapp

diff --git a/install-whatsapp b/install-whatsapp
--- a/install-whatsapp
+++ b/install-whatsapp
@@ -32,9 +32,9 @@ function success {
   echo -e "\\e[102;30m$1\\e[0m"
 }
 
-# To reduce annoying stderr output by apt 
+# To reduce some annoying output
 function reduceoutput { 
-  grep -v "apt does not have a stable CLI interface."
+  grep -v "apt does not have a stable CLI interface.\|snap "node" is already installed" 
 }
 
 # Check if user using root privilege to run this script
@@ -61,6 +61,8 @@ cd "$directory" | log || error  "Failed to cd to $directory"
 echo "Creating log file..."
 touch log.txt
 sleep 1
+echo ""
+success "Successfully created folder and log file."
 echo -e "\n"
 
 
@@ -69,10 +71,14 @@ progress "Identifying your system package manager..."
 echo ""
 if command -v apt > /dev/null; then
     packagemanager=apt
-    success "Your package manager is $packagemanager"
+    echo -e "Your package manager is \e[4m$packagemanager\e[0m"
+    echo ""
+    success "Successfully identified system package manager."
     echo -e "\\n"    
     progress "Updating package list..."
-    ( sudo $packagemanager update 2>&1 | log || error "Failed updating package list." ) | reduceoutput
+    ( sudo $packagemanager update 2>&1 | log || error "Failed updating package list." ) | tail -n +3
+    echo ""
+    success "Successfully updated package list."
     echo -e "\n"
 elif command -v dnf > /dev/null; then
     packagemanager=dnf
@@ -88,33 +94,50 @@ fi
 
 
 # Install snapd if not installed
+progress "Installing snap..."
+echo ""
 if ! command -v snap > /dev/null; then
-    progress "Installing snap..."
     sudo $packagemanager install snapd -y | reduceoutput
 else 
     success "Snap is already installed."
 fi
 
+echo -e "\n"
+
 # Installing node using snap
-sudo snap install node --classic
-if command -v node > /dev/null && command -v npm > /dev/null ; then 
-    success "Nodejs installed sucessfully."
-else 
-    error "Failed installing NodeJS. Try Try running 'sudo snap install node --classic' and run this script again."
-fi
+progress "Installing node..."
+echo ""
+snap info node | grep 'installed' > /dev/null | log
+if [ $? == 0 ]; then
+   success "Node is already installed."
+else
+    sudo snap install node --classic | reduceoutput
+    if command -v node > /dev/null && command -v npm > /dev/null ; then 
+        success "Nodejs installed sucessfully."
+    else 
+        error "Failed installing NodeJS. Try running 'snap install node --classic' or with sudo and run this script again."
+    fi
+fi 
+
+echo -e "\n"
 
 # Installing Nativefier
+progress "Installing Nativefier..."
+echo ""
 if ! command -v nativefier > /dev/null; then
-    success "Installing Nativefier..."
-    npm install -g nativefier | log || error  "Failed installing Nativefier. Try running 'npm install -g nativefier' and run this script again."
-cd "${HOME}/WhatsApp" | log || error  "Failed cd to WhatsApp folder."
-if command -v nativefier > /dev/null; then
-success "Nativefier installed successfully."
-fi
+    npm install -g nativefier | log || error  "Failed installing Nativefier. Try running 'npm install -g nativefier' or with sudo and run this script again."
+    if command -v nativefier > /dev/null; then
+        success "Nativefier installed successfully."
+    else 
+        error "Failed installing nativefier. Try running 'npm install -g nativefier' or with sudo and run this script again."
+    fi
 else 
-success "Nativefier is already installed."
+    success "Nativefier is already installed."
 fi
 
+
+cd "${HOME}/WhatsApp" | log || error  "Failed cd to WhatsApp folder."
+    
 # Identifying architecture
 arch=$(uname -m)
 
@@ -156,7 +179,9 @@ echo -e "\n"
 # Create desktop & menu shortcut
 progress "Creating desktop shortcut and menu shortcut..."
 echo ""
-cd "$directory" || error "Failed to cd to $directory."
+if  ! [ $(pwd) == $directory ]; then 
+    cd "$directory" || error "Failed to cd to $directory."
+fi
 git clone https://github.com/ITdairy/whatsapp-for-linux -v
 echo -e "\n"
 sudo cp $directory/whatsapp-for-linux/* ./ && sudo rm -rf $directory/whatsapp-for-linux
@@ -166,7 +191,8 @@ sudo cp $directory/whatsapp.desktop "$HOME/.local/share/applications" | log
 sudo cp $directory/whatsapp.desktop "$HOME/Desktop" | log
 sudo cp $directory/run-whatsapp $directory/WhatsApp-linux-$arch
 sudo chmod +x $directory/WhatsApp-linux-$arch/run-whatsapp
-echo -e "\n"
+success "Successfully created desktop and menu shortcut."
+echo -e "\n\n"
 success "Done! You should be able to run WhatsApp from desktop and menu bar."
 echo -e "\n\n"
 cd "$HOME"  || exit 
