Update installwhatsapp

diff --git a/installwhatsapp b/installwhatsapp
--- a/installwhatsapp
+++ b/installwhatsapp
@@ -2,32 +2,32 @@
 
 # Identifying the system package manager
 if command -v apt; then
-	packagemanager=apt
-	echo -e "\e[32mPackage manager is $packagemanager\e[0m" 
+    packagemanager=apt
+    echo -e "\\e[32mPackage manager is $packagemanager\\e[0m"
 elif command -v dnf; then
-	packagemanager=dnf
-	echo -e "\e[32mPackage manager is $packagemanager\e[0m" 
+    packagemanager=dnf
+    echo -e "\\e[32mPackage manager is $packagemanager\\e[0m"
 elif command -v yum; then
-	packagemanager=yum
-	echo -e "\e[32mPackage manager is $packagemanager\e[0m" 
-else 
-	echo -e "\e[41;5mPackage manager not found. This script only support apt, yum and dnf.\e[0m";
-    	exit 1
+    packagemanager=yum
+    echo -e "\\e[32mPackage manager is $packagemanager\\e[0m"
+else
+    echo -e "\\e[41;5mPackage manager not found. This script only support apt, yum and dnf.\\e[0m";
+    exit 1
 fi
 
 
 # Installing Nodejs and NPM
 if [ $packagemanager == 'apt' ]; then
-    echo -e "\e[32mAdding NodeSource...\e[0m"
-	curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - > /dev/null
-    echo -e "\e[32mRunning sudo apt update...\e[0m"
-	sudo apt update > /dev/null
+    echo -e "\\e[32mAdding NodeSource...\\e[0m"
+    curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - > /dev/null
+    echo -e "\\e[32mRunning sudo apt update...\\e[0m"
+    sudo apt update > /dev/null
     sudo apt install nodejs > /dev/null
-else 
-    echo -e "\e[32mAdding NodeSource...\e[0m"
-	curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash - > /dev/null
-	sudo $packagemanager check-update > /dev/null
-    echo -e "\e[32mRunning sudo $packagemanager update...\e[0m"    
+else
+    echo -e "\\e[32mAdding NodeSource...\\e[0m"
+    curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash - > /dev/null
+    sudo $packagemanager check-update > /dev/null
+    echo -e "\\e[32mRunning sudo $packagemanager update...\\e[0m"
     sudo $packagemanager install nodejs > /dev/null
 fi
 
@@ -35,35 +35,33 @@ fi
 # Installing Nativefier
 if command -v npm > /dev/null; then
     npm install -g nativefier
-	sudo mkdir $HOME/WhatsApp
-	cd $HOME/WhatsApp
-	wget https://raw.githubusercontent.com/ITdairy/whatsapp-for-linux/main/run-whatsapp.sh
-	wget https://raw.githubusercontent.com/ITdairy/whatsapp-for-linux/main/whatsapp.desktop
-	wget https://github.com/ITdairy/whatsapp-for-linux/raw/main/whatsapp.png
+    sudo mkdir "${HOME}/WhatsApp"
+    cd "${HOME}/WhatsApp" || exit 1
+    wget https://raw.githubusercontent.com/ITdairy/whatsapp-for-linux/main/run-whatsapp.sh
+    wget https://raw.githubusercontent.com/ITdairy/whatsapp-for-linux/main/whatsapp.desktop
+    wget https://github.com/ITdairy/whatsapp-for-linux/raw/main/whatsapp.png
 else
-	echo -e "\e[41;5mFailed. NPM not found.\e[0m"
-	exit 1
+    echo -e "\\e[41;5mFailed. NPM not found.\\e[0m"
+    exit 1
 fi
 
 
-#Nativefying WhatsApp 
+#Nativefying WhatsApp
 if command -v nativefier > /dev/null; then
-	echo -e '\e[32mNativefying WhatsApp from http://web.whatsapp.com ...\e[39m'
-	nativefier https://web.whatsapp.com --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" -a `uname -m` --maximize -n WhatsApp > /dev/null
-	sudo touch run-whatsapp
-	echo 'sudo rm -rf "$HOME/.config/whatsapp-nativefier-*/Service Worker" && $HOME/WhatsApp/WhatsApp-linux-`uname -m`/WhatsApp' > ./run-whatsapp
-	sudo chmod +x ./run-whatsapp
-	echo -e '\e[32mDone installing WhatsApp, Creating desktop shortcut and menu shortcut...'
-else 
-	echo -e "\e[41;5mFailed. Nativefier not found.\e[0m"
-	exit 1
+    echo -e '\\e[32mNativefying WhatsApp from http://web.whatsapp.com ...\\e[39m'
+    nativefier https://web.whatsapp.com --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" -a "$(uname -m)" --maximize -n WhatsApp > /dev/null
+    sudo touch run-whatsapp
+    echo "sudo rm -rf ${HOME}/.config/whatsapp-nativefier-*/Service Worker && $HOME/WhatsApp/WhatsApp-linux-$(uname -m)/WhatsApp" > ./run-whatsapp
+    sudo chmod +x ./run-whatsapp
+    echo -e '\\e[32mDone installing WhatsApp, Creating desktop shortcut and menu shortcut...'
+else
+    echo -e "\\e[41;5mFailed. Nativefier not found.\\e[0m"
+    exit 1
 fi
 
 
 #Create desktop & menu shortcut
-sudo cp ./whatsapp.desktop $HOME/.local/share/applications
-sudo cp ./whatsapp.desktop $HOME/Desktop
-echo -e '\e[32mDone! You should be able to run WhatsApp from desktop and menu bar.\e[39m'
-cd
-
-exit 0
+sudo cp ./whatsapp.desktop "$HOME/.local/share/applications"
+sudo cp ./whatsapp.desktop "$HOME/Desktop"
+echo -e '\\e[32mDone! You should be able to run WhatsApp from desktop and menu bar.\\e[39m'
+cd "$HOME"  || exit 0
